// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3B1SRfW-CSepy4j1PzwP5a5wlDBuzyMk',
    appId: '1:237015747549:web:4b1915719b68d82b038434',
    messagingSenderId: '237015747549',
    projectId: 'aneen-9f883',
    authDomain: 'aneen-9f883.firebaseapp.com',
    storageBucket: 'aneen-9f883.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRT36klfxP8CX_WUfE-pGpio7BllBOtYU',
    appId: '1:237015747549:android:0364cd4521134509038434',
    messagingSenderId: '237015747549',
    projectId: 'aneen-9f883',
    storageBucket: 'aneen-9f883.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxcyLRCEnynRxVVMOKV0SOzN9VZwlUoAk',
    appId: '1:237015747549:ios:1f95d59e3f1094de038434',
    messagingSenderId: '237015747549',
    projectId: 'aneen-9f883',
    storageBucket: 'aneen-9f883.appspot.com',
    iosClientId: '237015747549-491vj2hqjbpjmlrq61nppqv7mdln5ij6.apps.googleusercontent.com',
    iosBundleId: 'com.example.aneen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxcyLRCEnynRxVVMOKV0SOzN9VZwlUoAk',
    appId: '1:237015747549:ios:a4093833ac4333ff038434',
    messagingSenderId: '237015747549',
    projectId: 'aneen-9f883',
    storageBucket: 'aneen-9f883.appspot.com',
    iosClientId: '237015747549-ogaksl62v720jraa637fc8d8ta80d5pl.apps.googleusercontent.com',
    iosBundleId: 'com.example.aneen.RunnerTests',
  );
}
